<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssr.proto

namespace GPBMetadata;

class Ssr
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
À
	ssr.protoSsr"+
RenderRequest
page (	
data (	"
RenderResponse
html (	2C

SSRService5

RenderPage.Ssr.RenderRequest.Ssr.RenderResponseBÊItb\\Ssr\\Generatedbproto3'
        , true);

        static::$is_initialized = true;
    }
}

